// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {screen} from '../models';
import {config} from '../models';

export function CancelRunningTask():Promise<boolean>;

export function CheckScreenCapturePermission():Promise<boolean>;

export function ClearResume():Promise<void>;

export function CopyCode():Promise<void>;

export function EmitEvent(arg1:string,arg2:Array<any>):Promise<void>;

export function GetInitStatus():Promise<string>;

export function GetModels(arg1:string,arg2:string):Promise<Array<string>>;

export function GetResumePDF():Promise<string>;

export function GetScreenshotPreview(arg1:number,arg2:number,arg3:boolean,arg4:boolean,arg5:string):Promise<screen.PreviewResult>;

export function GetSettings():Promise<config.Config>;

export function IsInterruptThinkingEnabled():Promise<boolean>;

export function MoveWindow(arg1:number,arg2:number):Promise<void>;

export function OpenScreenCaptureSettings():Promise<void>;

export function ParseResume():Promise<string>;

export function RemoveFocus():Promise<void>;

export function RequestScreenCapturePermission():Promise<boolean>;

export function RestoreFocus():Promise<void>;

export function SaveImageToFile(arg1:string):Promise<boolean>;

export function ScrollContent(arg1:string):Promise<void>;

export function SelectResume():Promise<string>;

export function SetWindowAlwaysOnTop(arg1:boolean):Promise<void>;

export function StartLiveSession():Promise<void>;

export function StartRecordingKey(arg1:string):Promise<void>;

export function StopLiveSession():Promise<void>;

export function StopRecordingKey():Promise<void>;

export function SyncSettingsToDefaultSettings(arg1:string):Promise<string>;

export function TestConnection(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ToggleClickThrough():Promise<void>;

export function ToggleVisibility():Promise<void>;

export function TriggerSolve():Promise<void>;

export function UpdateSettings(arg1:string):Promise<string>;
