// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelRunningTask() {
  return window['go']['main']['App']['CancelRunningTask']();
}

export function CheckScreenCapturePermission() {
  return window['go']['main']['App']['CheckScreenCapturePermission']();
}

export function ClearResume() {
  return window['go']['main']['App']['ClearResume']();
}

export function CopyCode() {
  return window['go']['main']['App']['CopyCode']();
}

export function EmitEvent(arg1, arg2) {
  return window['go']['main']['App']['EmitEvent'](arg1, arg2);
}

export function GetInitStatus() {
  return window['go']['main']['App']['GetInitStatus']();
}

export function GetModels(arg1, arg2) {
  return window['go']['main']['App']['GetModels'](arg1, arg2);
}

export function GetResumePDF() {
  return window['go']['main']['App']['GetResumePDF']();
}

export function GetScreenshotPreview(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetScreenshotPreview'](arg1, arg2, arg3, arg4, arg5);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function IsInterruptThinkingEnabled() {
  return window['go']['main']['App']['IsInterruptThinkingEnabled']();
}

export function MoveWindow(arg1, arg2) {
  return window['go']['main']['App']['MoveWindow'](arg1, arg2);
}

export function ParseResume() {
  return window['go']['main']['App']['ParseResume']();
}

export function RemoveFocus() {
  return window['go']['main']['App']['RemoveFocus']();
}

export function RequestScreenCapturePermission() {
  return window['go']['main']['App']['RequestScreenCapturePermission']();
}

export function RestoreFocus() {
  return window['go']['main']['App']['RestoreFocus']();
}

export function SaveImageToFile(arg1) {
  return window['go']['main']['App']['SaveImageToFile'](arg1);
}

export function ScrollContent(arg1) {
  return window['go']['main']['App']['ScrollContent'](arg1);
}

export function SelectResume() {
  return window['go']['main']['App']['SelectResume']();
}

export function StartLiveSession() {
  return window['go']['main']['App']['StartLiveSession']();
}

export function StartRecordingKey(arg1) {
  return window['go']['main']['App']['StartRecordingKey'](arg1);
}

export function StopLiveSession() {
  return window['go']['main']['App']['StopLiveSession']();
}

export function StopRecordingKey() {
  return window['go']['main']['App']['StopRecordingKey']();
}

export function SyncSettingsToDefaultSettings(arg1) {
  return window['go']['main']['App']['SyncSettingsToDefaultSettings'](arg1);
}

export function TestConnection(arg1, arg2, arg3) {
  return window['go']['main']['App']['TestConnection'](arg1, arg2, arg3);
}

export function ToggleClickThrough() {
  return window['go']['main']['App']['ToggleClickThrough']();
}

export function ToggleVisibility() {
  return window['go']['main']['App']['ToggleVisibility']();
}

export function TriggerSolve() {
  return window['go']['main']['App']['TriggerSolve']();
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
